version: 2.1
executors:
  golang:
    docker:
    - image: cimg/go:1.15
  docker:
    docker:
      - image: docker:stable-git

jobs:

  build:
    executor: golang
    steps:
      - checkout
      - run: make style vet test build integ

  image:
    environment:
        IMAGE_NAME: ncabatoff/process-exporter
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:latest .

  image_master:
    environment:
        IMAGE_NAME: ncabatoff/process-exporter
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:master .
      - run: |
          echo "$DOCKERHUB_PASSWORD"| docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME:master

  release:
    executor: golang
    steps:
      - checkout
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -y rpm
      - run: echo "export BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV
      - run: curl -sL https://git.io/goreleaser | VERSION=v0.146.0 bash

  release_image:
    environment:
      IMAGE_NAME: ncabatoff/process-exporter
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          IMAGE_TAG=${CIRCLE_TAG/v/''}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          echo "$DOCKERHUB_PASSWORD"| docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

workflows:
  version: 2
  build_and_image:
    jobs:
      - build
      - image
  master:
    jobs:
      - image_master:
          filters:
            branches:
              only: master
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release_image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
